# Generated by Django 3.2.6 on 2023-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='pas',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
