# Generated by Django 3.2.6 on 2023-03-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_auto_20230314_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='pas',
            new_name='password',
        ),
    ]
